spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:~/test;
    driverClassName: org.h2.Driver
    password: ''

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.flab.todo.database.model
  mapper-locations: mybatis-mapper/*.xml
